---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine"
    - image="alpine" tag="edge"
    # - namespace="archlinux" image="base"
    - image="debian" tag="stable"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos" tag="7"
    - image="centos"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="ubuntu" tag="rolling"
    - image="ubuntu" tag="devel"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"
    - env: image="ubuntu" tag="rolling"
    - env: image="ubuntu" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "ZmTVyISHBKSrPwAIuKRvUJiRd1t8ao1nmC5qUkxSbN1Hr4shwu9Ulf4/hS/mF1jBxrHZrv3aiihIHyNl74f6j/+S1uqmeerSeLtZJTUFT+ys/BCBpAXFgM8zml0jTiep1o2V5SSWYkJmbbehHeVA8PCSLhc6wUb8yhKpuhs+6mpiMch7Zv9gwZL1dlzUUPBzBl5pGBc7pgmwGMleQ/EGQ+/0QTMpehCCopIyuotv8TGeYyR9KvwS/Nt1XanGc5la7WBLDGgfrvEFeMYUgTTRukBuDy8B90tolJCYD6lwZVp52J1bxEgQsCoiR5zH3D9o0p7tqFAJWGCUb0mFngrqv4r2GGPL3xCAU9TI0uf2lHZ7coZ3nBxCadxGTniYIstmRxTryddA5L7u0R4Bwae92NEG5jsK2kPKV/SXe+w5ckGkRSHL5mZiH9Vatmy+fX+mV8oZHehQTlH9zeSwZ+AKwSC7GKbEWRkPlfv+IAZKzkJXazUBkCUmOYH39/1iwmQfVUy0ZoLoHzSo1YQR60RVOTsn2WrDrnR+v3NmcUOF/a7224M1MHJCC8qw6xnTQGAIXAzCLZ/btK4QZD1fDjUNKV6mzBlJlovauNeuEG+JaVN2bN0k5AFRBv5NMNnLUlR97XpjRR8SNaEIB0bq6Ek38EERPDlMeIrJqi5tQXABmAg="
  email: false
