---
- name: test if cntlm_version is set correctly
  assert:
    that:
      - cntlm_version is defined
    quiet: yes

- name: test if cntlm_release is set correctly
  assert:
    that:
      - cntlm_release is defined
      - cntlm_release is number
      - cntlm_release | int
      - cntlm_release | int > 0
    quiet: yes

- name: test if cntlm_download_mirror is set correctly
  assert:
    that:
      - cntlm_download_mirror is defined
    quiet: yes

- name: test if cntlm_username is set correctly
  assert:
    that:
      - cntlm_username is defined
    quiet: yes

- name: test if cntlm_password is set correctly
  assert:
    that:
      - cntlm_password is defined
    quiet: yes

- name: test if cntlm_domain is set correctly
  assert:
    that:
      - cntlm_domain is defined
    quiet: yes

- name: test if cntlm_proxy is set correctly
  assert:
    that:
      - cntlm_proxy is defined
    quiet: yes

- name: test if cntlm_listen is set correctly
  assert:
    that:
      - cntlm_listen is defined
      - cntlm_listen is number
      - cntlm_listen | int > 0
      - cntlm_listen | int < 65536
    quiet: yes

- name: test if cntlm_passntlmv2 is set correctly
  assert:
    that:
    quiet: yes
  when:
    - cntlm_passntlmv2 is defined

- name: test if cntlm_noproxy is set correctly
  assert:
    that:
      - cntlm_noproxy is defined
    quiet: yes

- name: test if cntlm_tmp is set correctly
  assert:
    that:
      - cntlm_tmp is defined
    quiet: yes

- name: test if cntlm_allows is set correctly
  assert:
    that:
      - cntlm_allows is defined
      - cntlm_allows is iterable
    quiet: yes

- name: test if cntlm_denies is set correctly
  assert:
    that:
      - cntlm_denies is defined
      - cntlm_denies is iterable
    quiet: yes

- name: test if gateway_enabled is set correctly
  assert:
    that:
      - gateway_enabled is defined
      - gateway_enabled in [ "yes", "no" ]
    quiet: yes
