---
# tasks file for cntlm

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ cntlm_requirements }}"
    state: present

- name: unpack cntlm software
  unarchive:
    src: "{{ cntlm_sourceforge_mirror }}/{{ cntlm_archive }}"
    dest: "{{ cntlm_tmp }}"
    remote_src: yes
    mode: "0755"
  when:
    - ansible_pkg_mgr not in [ "apt", "yum", "dnf" ]
  notify:
    - configure cntlm
    - make cntlm
    - install cntlm

- name: install cntlm software
  package:
    name: cntlm
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr in [ "yum" ]

- name: install cntlm software (dnf)
  dnf:
    name: "{{ cntlm_rpm_repository }}"
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr [ "dnf" ]

- name: manage apt details
  block:
    - name: download cntlm software (deb)
      get_url:
        url: "{{ cntlm_dpkg_repository }}"
        dest: "{{ cntlm_tmp }}/cntlm_{{ cntlm_version }}_amd64.deb"
        validate_certs: no

    - name: install cntlm software (apt)
      apt:
        deb: "{{ cntlm_tmp }}/cntlm_{{ cntlm_version }}_amd64.deb"
        state: present
  when:
    - ansible_pkg_mgr in [ "apt" ]

- name: create cntlm service
  import_role:
    name: robertdebock.service

- name: generate hash
  shell: "set -o pipefail ; {{ cntlm_hash_command }} | tee /etc/cntlm.hash"
  args:
    creates: /etc/cntlm.hash
    executable: /bin/bash
  register: cntlm_generate_hash
  check_mode: no
  notify:
    - configure cntlm.conf

- name: start and enable cntlm
  service:
    name: cntlm
    state: started
    enabled: yes
