---
# tasks file for cntlm
- name: install requirements
  package:
    name: "{{ cntlm_stable_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default (cntlm_stable_packages[ansible_distribution]
          | default (cntlm_stable_packages['default'] )) }}"
    state: "{{ cntlm_package_state }}"

- name: unpack cntlm software
  unarchive:
    src: "{{ cntlm_sourceforge_mirror }}/{{ cntlm_archive }}"
    dest: /tmp
    remote_src: yes
  register: unpack_software
  until: unpack_software is succeeded
  retries: 5
  delay: 3
  when:
    - ansible_pkg_mgr != "apt"
    - ansible_pkg_mgr != "yum"
    - ansible_pkg_mgr != "dnf"
  notify:
    - configure cntlm
    - make cntlm
    - install cntlm

- name: install cntlm software (dnf)
  dnf:
    name: https://{{ cntlm_download_mirror }}/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm-{{ cntlm_version }}-{{ cntlm_release }}.x86_64.rpm
    state: present
  when:
    - ansible_pkg_mgr == "dnf"

- name: install cntlm software (yum)
  yum:
    name: https://{{ cntlm_download_mirror }}/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm-{{ cntlm_version }}-{{ cntlm_release }}.x86_64.rpm
    state: present
    validate_certs: no
  when:
    - ansible_pkg_mgr == "yum"
  register: install_software
  until: install_software is succeeded
  retries: 5
  delay: 3

- name: download cntlm software (deb)
  get_url:
    url: https://{{ cntlm_download_mirror }}/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm_{{ cntlm_version }}_amd64.deb
    dest: /tmp/cntlm_{{ cntlm_version }}_amd64.deb
    validate_certs: no
  when:
    - ansible_pkg_mgr == "apt"
  register: download_software
  until: download_software is succeeded
  retries: 5
  delay: 3

- name: install cntlm software (apt)
  apt:
    deb: /tmp/cntlm_{{ cntlm_version }}_amd64.deb
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: register cntlm to a systemd system
  template:
    src: cntlm.service.j2
    dest: /etc/systemd/system/cntlm.service
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - systemctl daemon-reload

- name: configure cntlm
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf
  notify:
    - restart cntlm

- name: start and enable cntlm
  service:
    name: cntlm
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
