---
# tasks file for cntlm
- name: install software (yum/dnf)
  yum:
    name: https://vorboss.dl.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm-0.92.3-1.x86_64.rpm
    validate_certs: no
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: install software (apt)
  apt:
    name: https://vorboss.dl.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm_0.92.3_amd64.deb
  when:
    - ansible_pkg_mgr == "apt"

# targz contains source, would be quite some extra work to compile instead
# of install.
#
#- name: download software (targz)
#  unarchive:
#    src: https://vorboss.dl.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm-0.92.3.tar.gz
#    dest: /tmp
#    remote_src: yes
#  when:
#    - ansible_pkg_mgr != "yum"
#    - ansible_pkg_mgr != "apt"

- name: configure software
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf

- name: start software
  service:
    name: cntlm
    state: started
    enabled: yes
