---
# tasks file for cntlm
- name: install software (yum/dnf)
  yum:
    name: https://vorboss.dl.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm-0.92.3-1.x86_64.rpm
    validate_certs: no
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: download software (deb)
  get_url:
    url: https://vorboss.dl.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm_0.92.3_amd64.deb
    dest: /tmp
    validate_certs: no

- name: install software (apt)
  package:
    name: /tmp/cntlm_0.92.3_amd64.deb
  when:
    - ansible_pkg_mgr == "apt"

- name: register cntlm to a systemd system
  template:
    src: cntlm.service.j2
    dest: /etc/systemd/system/cntlm.service
  when:
    - ansible_service_mgr == "systemd"

- name: configure software
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf

- name: start software
  service:
    name: cntlm
    state: started
    enabled: yes
