---
# tasks file for cntlm
- name: unpack software
  unarchive:
    src: "{{ cntlm_sourceforge_mirror }}/{{ cntlm_archive }}"
    dest: /tmp/cntlm_{{ cntlm_version }}
    remote_src: yes
  register: unpack_software
  until: unpack_software is succeeded
  retries: 5
  delay: 3
  when:
    - ansible_pkg_mgr != "apt"
    - ansible_pkg_mgr != "yum"
    - ansible_pkg_mgr != "dnf"

- name: configure software
  command: ./configure
  args:
    chdir: /tmp/cntlm_{{ cntlm_version }}
    creates: /tmp/cntlm/config/config.h

- name: make software
  make:
    chdir: /tmp/cntlm_{{ cntlm_version }}

- name: install software
  copy:
    src: /tmp/cntlm_{{ cntlm_version }}/cntlm
    dest: /usr/sbin/cntlm
    owner: root
    group: root
    mode: 0755

- name: install software (dnf)
  dnf:
    name: https://{{ cntlm_download_mirror }}/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm-{{ cntlm_version }}-{{ cntlm_release }}.x86_64.rpm
  when:
    - ansible_pkg_mgr == "dnf"

- name: install software (yum)
  yum:
    name: https://{{ cntlm_download_mirror }}/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm-{{ cntlm_version }}-{{ cntlm_release }}.x86_64.rpm
    validate_certs: no
  when:
    - ansible_pkg_mgr == "yum"
  register: install_software
  until: install_software is succeeded
  retries: 5
  delay: 3

- name: download software (deb)
  get_url:
    url: https://{{ cntlm_download_mirror }}/project/cntlm/cntlm/cntlm%20{{ cntlm_version }}/cntlm_{{ cntlm_version }}_amd64.deb
    dest: /tmp/cntlm_{{ cntlm_version }}_amd64.deb
    validate_certs: no
  when:
    - ansible_pkg_mgr == "apt"
  register: download_software
  until: download_software is succeeded
  retries: 5
  delay: 3

- name: install software (apt)
  apt:
    deb: /tmp/cntlm_{{ cntlm_version }}_amd64.deb
  when:
    - ansible_pkg_mgr == "apt"

- name: register cntlm to a systemd system
  template:
    src: cntlm.service.j2
    dest: /etc/systemd/system/cntlm.service
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - systemctl daemon-reload

- name: configure software
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf

- name: start and enable software
  service:
    name: cntlm
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
