---
# handlers file for cntlm
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  notify:
    - restart software

- name: configure cntlm
  command: ./configure
  args:
    chdir: "{{ cntlm_tmp }}/cntlm-{{ cntlm_version }}"
    creates: "{{ cntlm_tmp }}/cntlm/config/config.h"

- name: make cntlm
  command: make -j {{ ansible_processor_vcpus * 2 }}
  args:
    chdir: "{{ cntlm_tmp }}/cntlm-{{ cntlm_version }}"

- name: install cntlm
  copy:
    src: "{{ cntlm_tmp }}/cntlm-{{ cntlm_version }}/cntlm"
    dest: /usr/sbin/cntlm
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: configure cntlm.conf
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf
  notify:
    - restart cntlm

- name: restart cntlm
  service:
    name: cntlm
    state: restarted
